FROM registry.suse.com/bci/dotnet-sdk:7.0 as builder

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
RUN zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends git-core nodejs20 npm20 python311 python311-pip wget zip unzip make gawk \
    && dotnet --list-sdks \
    && zypper clean -a

CMD /bin/bash
