name: Build and Upload extra cdxgen plugins

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  linux_arm64_builder:
    runs-on: [self-hosted, arm64]
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'CycloneDX/cdxgen-plugins-bin'
    - uses: oras-project/setup-oras@v1
    - run: oras version
    - name: Build
      run: |
        bash thirdparty/sourcekitten/build.sh
        ls -l thirdparty/sourcekitten/SourceKitten/.build/release
        echo $GITHUB_TOKEN | oras login ghcr.io -u $GITHUB_USERNAME --password-stdin
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload linux arm64
      run: |
        cd thirdparty/sourcekitten/SourceKitten/.build/release/
        oras push ghcr.io/appthreat/cdxgen-plugins-bin:linux-arm64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./sourcekitten:application/vnd.cyclonedx.plugins.layer.v1+tar \
          ./sourcekitten.sha256:application/vnd.cyclonedx.plugins.layer.v1+tar
